apiVersion: postgres-operator.crunchydata.com/v1
kind: PostgresCluster
metadata:
  name: mm-mattermost
spec:
  postgresVersion: 18
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  users:
    - name: mm-mattermost
      databases:
        - mm-mattermost
      options: 'SUPERUSER'
  service:
    metadata:
      annotations:
        my-annotation: mm-mattermost
      labels:
        my-label: mm-mattermost
    type: NodePort
    nodePort: 31002
  monitoring:
    pgmonitor:
      exporter: {}
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 20Gi
  proxy:
    pgBouncer: {}
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - host mm-mattermost m-mattermost 10.1.77.8/32 md5
          - local all all peer
          - host all all 0.0.0.0/0 md5