{
 "title": "PGBouncer",
 "tags": [ "vendor=crunchydata" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "query": {
     "query": "label_values(up{exp_type='pgbouncer'},cluster_name)"
    }
   },
   {
    "name": "pgbnode",
    "query": {
     "query": "label_values(up{cluster_name=\"[[cluster_name]]\",exp_type='pgbouncer'},pod)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values(ccp_pgbouncer_databases_pool_size{cluster_name=\"[[cluster_name]]\", pod=\"[[pgbnode]]\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PGBouncer Total State Counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ccp_pgbouncer_pools_client_active{cluster_name=~\"[[cluster_name]]\",pod=~\"[[pgbnode]]\"})",
     "legendFormat": "client_active"
    },
    {
     "expr": "sum(ccp_pgbouncer_pools_client_waiting{cluster_name=~\"[[cluster_name]]\",pod=~\"[[pgbnode]]\"})",
     "legendFormat": "client_waiting"
    },
    {
     "expr": "sum(ccp_pgbouncer_pools_server_active{cluster_name=~\"[[cluster_name]]\",pod=~\"[[pgbnode]]\"})",
     "legendFormat": "server_active"
    },
    {
     "expr": "sum(ccp_pgbouncer_pools_server_idle{cluster_name=~\"[[cluster_name]]\",pod=~\"[[pgbnode]]\"})",
     "legendFormat": "server_idle"
    },
    {
     "expr": "sum(ccp_pgbouncer_pools_server_used{cluster_name=~\"[[cluster_name]]\",pod=~\"[[pgbnode]]\"})",
     "legendFormat": "server_used"
    }
   ]
  },
  {
   "title": "PGBouncer Total Item Counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ccp_pgbouncer_lists_item_count{cluster_name=~\"[[cluster_name]]\",pod=~\"[[pgbnode]]\"}",
     "legendFormat": "{{list}}"
    }
   ]
  },
  {
   "title": "Connection % Used Per Pool ([[pool]])",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ccp_pgbouncer_databases_current_connections{cluster_name=~\"[[cluster_name]]\", pod=~\"[[pgbnode]]\", name=~\"[[pool]]\"} / ccp_pgbouncer_databases_pool_size{cluster_name=~\"[[cluster_name]]\", pod=~\"[[pgbnode]]\", name=~\"[[pool]]\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Client Connection State Counts Per Pool  ([[pool]])",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ccp_pgbouncer_clients_wait_seconds{cluster_name=~\"[[cluster_name]]\",pod=~\"[[pgbnode]]\", database=~\"[[pool]]\"}) by (pool,state)",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Server Connection State Counts Per Pool  ([[pool]])",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ccp_pgbouncer_servers_close_needed{cluster_name=~\"[[cluster_name]]\",pod=~\"[[pgbnode]]\", database=~\"[[pool]]\"}) by (state)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}