{
 "title": "Pod Details",
 "tags": [ "vendor=crunchydata" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(pg_cluster)" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(pg_up{pg_cluster=\"[[cluster]]\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_replication_is_replica{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_replication_lag_seconds{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"})*100/sum(pg_settings_max_connections{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"})"
    }
   ]
  },
  {
   "title": "Connections by State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\", state=\"active\"}",
     "legendFormat": "active ({{datname}})"
    },
    {
     "expr": "pg_stat_activity_count{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\", state=\"idle\"}",
     "legendFormat": "idle ({{datname}})"
    },
    {
     "expr": "pg_stat_activity_count{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\", state=\"idle in transaction\"}",
     "legendFormat": "idle in txn ({{datname}})"
    }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"}[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Row Activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_updated{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_deleted{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"}[5m]))",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_bgwriter_buffers_alloc_total{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(pg_stat_bgwriter_buffers_backend_total{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum(pg_stat_bgwriter_buffers_clean_total{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"})",
     "legendFormat": "Clean"
    },
    {
     "expr": "sum(pg_stat_bgwriter_buffers_checkpoint_total{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"})",
     "legendFormat": "Checkpoint"
    }
   ]
  },
  {
   "title": "WAL Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_wal_size_bytes{pod=\"[[pod]]\", pg_cluster=\"[[cluster]]\"}",
     "legendFormat": "WAL Size"
    }
   ]
  }
 ]
}