{
 "title": "PostgreSQLDetails",
 "tags": [ "vendor=crunchydata" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(pg_cluster)" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(pg_up{pg_cluster=\"[[cluster]]\"},pod)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values({pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"},datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\", state=\"active\"})*100 /sum(pg_settings_max_connections{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})"
    }
   ]
  },
  {
   "title": "Idle In Transaction",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",state=\"idle in transaction\"})/sum(pg_settings_max_connections{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})"
    }
   ]
  },
  {
   "title": "Max Transaction Duration",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_stat_activity_max_tx_duration{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",state=\"idle\"})*100/sum(pg_settings_max_connections{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})"
    }
   ]
  },
  {
   "title": "% Toward Wraparound",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ccp_transaction_wraparound_percent_towards_wraparound{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})*100/sum(pg_stat_database_blks_hit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}+pg_stat_database_blks_read{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})"
    }
   ]
  },
  {
   "title": "Activity -  [[pod]]-[[datname]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m])) + sum(irate(pg_stat_database_xact_rollback{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Connections -  [[pod]]-[[datname]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",state=\"idle\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum by (state) (pg_stat_activity_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",state=\"idle in transaction\"})",
     "legendFormat": "Idle in txn"
    },
    {
     "expr": "sum by (state) (pg_stat_activity_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",state=\"active\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "database size - [[pod]]-[[datname]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})/(1024*1024)",
     "legendFormat": "Total : [[cluster]]-[[pod]]"
    },
    {
     "expr": "pg_database_size_bytes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}/(1024*1024)",
     "legendFormat": "{{datname}} ({{pod}})"
    }
   ]
  },
  {
   "title": "Row activity - [[pod]]-[[datname]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_updated{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_deleted{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Deleted"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_returned{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "WAL size MB - [[cluster]]-[[pod]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "pg_wal_size_bytes{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"}/(1024*1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Key Counters - [[pod]] - [[datname]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_deadlocks{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Conflicts"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "DeadLocks"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\"}[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Replication Lag - [[cluster]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Lag bytes" }
   ],
   "targets": [
    {
     "expr": "pg_replication_lag_seconds{pg_cluster=\"[[cluster]]\"}",
     "legendFormat": "Lag seconds ({{pod}})"
    }
   ]
  },
  {
   "title": "Buffers - [[pod]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_bgwriter_buffers_alloc_total{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(pg_stat_bgwriter_buffers_backend_total{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum(pg_stat_bgwriter_buffers_backend_fsync_total{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})",
     "legendFormat": "FSync"
    },
    {
     "expr": "sum(pg_stat_bgwriter_buffers_checkpoint_total{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})",
     "legendFormat": "CheckPoint"
    },
    {
     "expr": "sum(pg_stat_bgwriter_buffers_clean_total{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\"})",
     "legendFormat": "Clean"
    }
   ]
  },
  {
   "title": "Locks - [[pod]]-[[datname]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",mode=\"accessexclusivelock\"})",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",mode=\"exclusivelock\"})",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",mode=\"rowexclusivelock\"})",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",mode=\"sharerowexclusivelock\"})",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",mode=\"shareupdateexclusivelock\"})",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname=~\"[[datname]]\",mode=\"accesssharelock\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio - [[pod]]-[[datname]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\", datname!~\"template0\", datname!~\"template1\"}*100/(pg_stat_database_blks_hit{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\", datname!~\"template0\", datname!~\"template1\"} + pg_stat_database_blks_read{pg_cluster=\"[[cluster]]\",pod=~\"[[pod]]\",datname!~\"template0\", datname!~\"template1\"})",
     "legendFormat": "{{datname}} - ({{pod}})"
    }
   ]
  }
 ]
}