apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: crunchy-grafana
  labels:
    dashboards: crunchy-grafana
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
          - name: grafana
            env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: username
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: password
