apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-pgo
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: grafana-pgo
  annotations:
    kubernetes.io/service-account.name: grafana-pgo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-pgo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: grafana-pgo
  namespace: postgres-operator
