apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
<<<<<<< HEAD
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.3-2
=======
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.3-0
>>>>>>> 0bb94ef (Issue [sc-19704])
  postgresVersion: 15
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
<<<<<<< HEAD
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-2
=======
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-0
>>>>>>> 0bb94ef (Issue [sc-19704])
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
