apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  postgresVersion: 16
  # image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:$POSTGRES_16_TAG
  users:
    - name: rhino
      databases:
        - zoo
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      # image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:$PGBACKREST_TAG
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
