kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: postgres-operator

resources:
# Configuration
  - ./config
# Volumes
  - pvcs.yaml
# RBAC
  - rbac-sa.yaml
  - rbac-cr.yaml
  - rbac-crb.yaml
# Deployments
  - deploy-alertmanager.yaml
  - deploy-grafana.yaml
  - deploy-prometheus.yaml
# Services
  - service.yaml
