apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    vendor: crunchydata
  name: prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    vendor: crunchydata
  name: alertmanager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    vendor: crunchydata
  name: grafana
