kind: pipeline
type: kubernetes
name: devops-service

services:
  - name: docker
    image: docker:dind
    command: [ "--storage-driver=vfs", "--tls=false" ]
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ''
    
concurrency:
  limit: 1

trigger:
  event:
    exclude:
    - pull_request

steps:

  - name: push containers
    image: docker:latest
    commands:
      - sleep 30
      - docker --tls=false ps
      - apk update && apk add curl python3 py3-pip
      - pip3 install shyaml
      - sh ./push_and_tag.sh
    
    environment:
      GCR_CREDENTIALS:
        from_secret: gcr_credentials
      HARBOR_PASSWORD:
        from_secret: harbor_password
      HARBOR_USERNAME:
        from_secret: harbor_username
      CRUNCHY_PASSWORD:
        from_secret: crunchy_sa_password
      CRUNCHY_USERNAME:
        from_secret: crunchy_sa_username
      DOCKER_HOST: tcp://docker:2375
    when:
      branch:
        - main
        
  - name: push helm charts
    image: alpine/helm
    commands:
      - helm version
      - helm plugin install https://github.com/chartmuseum/helm-push
      - helm repo add --username $USERNAME --password $PASSWORD harbor https://harbor.devops.indico.io/chartrepo/indico-charts
      - sh upload_helm_charts.sh 
    
    environment:
      HELM_EXPERIMENTAL_OCI: 1
      PASSWORD:
        from_secret: harbor_password
      USERNAME:
        from_secret: harbor_username
    when:
      branch:
        - main

  
      

image_pull_secrets:
  - harbor_pull_secret

---
kind: secret
name: harbor_pull_secret
get:
  path: tools/drone/devops_harbor_pull_secret
  name: DOCKER_CONFIG_JSON 

---
kind: secret
name: harbor_username
get:
  path: tools/drone/harbor-push-token
  name: username

---
kind: secret
name: harbor_password
get:
  path: tools/drone/harbor-push-token
  name: password

---
kind: secret
name: gcr_credentials
get:
  path: tools/drone/devops_gcr_credentials
  name: data

---
kind: secret
name: crunchy_sa_password
get:
  path: tools/drone/crunchy_sa
  name: password

---
kind: secret
name: crunchy_sa_username
get:
  path: tools/drone/crunchy_sa
  name: username