{{- if or .Values.multiBackupRepos .Values.s3 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default .Release.Name .Values.name }}-pgbackrest-secret
type: Opaque
data:
{{- if .Values.multiBackupRepos }}
  {{- range $index, $repo := .Values.multiBackupRepos }}
  {{- if $repo.s3 }}
  {{- $args := dict "s3" $repo.s3 "index" $index }}
  s3.conf: |-
        {{ include "postgres.s3" $args | b64enc }}
  {{- end }}
{{- end }}
{{- else if .Values.s3 }}
  {{- $args := dict "s3" .Values.s3 "index" 0 }}
  s3.conf: |-
        {{ include "postgres.s3" $args | b64enc }}
{{- end }}
{{- end }}
