---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: postgres-operator-upgrade
  labels:
    postgres-operator.crunchydata.com/control-plane: postgres-operator-upgrade
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - list
  - patch
  - watch
- apiGroups:
  - postgres-operator.crunchydata.com
  resources:
  - pgupgrades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres-operator.crunchydata.com
  resources:
  - pgupgrades/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - postgres-operator.crunchydata.com
  resources:
  - pgupgrades/status
  verbs:
  - get
  - patch
- apiGroups:
  - postgres-operator.crunchydata.com
  resources:
  - postgresclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres-operator.crunchydata.com
  resources:
  - postgresclusters/status
  verbs:
  - patch
