apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: crunchy-prometheus

resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml

configMapGenerator:
- files:
  - config/prometheus.yml
  name: crunchy-prometheus
- files:
  - config/crunchy-alert-rules-pg.yml
  name: alert-rules-config

generatorOptions:
  disableNameSuffixHash: true
