namespace: zoo

nameSuffix: -standby

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: pgo-s3-creds
  files:
  - s3.conf

bases:
  - ../../base/postgres

patchesStrategicMerge:
  - postgres.yaml


