apiVersion: v2
name: postgresapp
description: A Helm chart deployment of the Postgres Operator and Postgrs cluster
type: application
version: 5.5.1
appVersion: 5.5.1
dependencies:
  - name: pgo
    version: 5.5.1
    repository: "file://../install"
    condition: pgo.enabled
  - name: postgrescluster
    version: 5.5.1
    repository: "file://../postgres"
    condition: postgrescluster.enabled
