apiVersion: postgres-operator.crunchydata.com/v1
kind: PostgresCluster
metadata:
  name: keycloak
spec:
  postgresVersion: 18
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi  # Zwiększone dla production
  users:
    - name: keycloak
      databases:
        - keycloak
      options: 'SUPERUSER'
  
  service:
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb  # Lepsze dla production
      labels:
        app: keycloak-postgres
    type: LoadBalancer
    # Usuń nodePort - będzie przydzielony automatycznie
  
  patroni:
    dynamicConfiguration:
      pg_hba:
        - "hostssl all all all md5"  # Używaj SSL
  
  monitoring:
    pgmonitor:
      exporter: {}
  
  backups:
    pgbackrest:
      repos:
      - name: repo1
        schedules:
          full: "0 2 * * 0"        # Pełny backup w niedzielę o 2:00
          differential: "0 2 * * 1-6"  # Różnicowy backup codziennie o 2:00
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi  # Większe dla backupów production
  
  proxy:
    pgBouncer: {}
