apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: postgres-operator
  labels:
    app.kubernetes.io/name: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
      - image: quay.io/keycloak/keycloak:latest
        args: ["start-dev"]
        name: keycloak
        env:
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL_HOST
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: host } }
        - name: KC_DB_URL_PORT
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: port } }
        - name: KC_DB_URL_DATABASE
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: dbname } }
        - name: KC_DB_USERNAME
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: user } }
        - name: KC_DB_PASSWORD
          valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: password } }
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY_HEADERS
          value: "xforwarded"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
      restartPolicy: Always
