apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      containers:
        - image: quay.io/keycloak/keycloak:17.0.1
          name: keycloak
          args: ["start-dev"]
          resources: {}
          env:
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: jdbc-uri } }
            - name: KC_DB_USER
              valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: user } }
            - name: KC_DB_PASSWORD
              valueFrom: { secretKeyRef: { name: keycloakdb-pguser-keycloakdb, key: password } }
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "admin"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KC_PROXY
              value: "edge"              
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
      restartPolicy: Always