apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: keycloakdb
spec:
  image: us.gcr.io/container-suite/crunchy-postgres-ha:ubi8-13.2-ci-latest
  postgresVersion: 13
  openshift: false
  instances:
    - replicas: 2
      volumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  archive:
    pgbackrest:
      image: us.gcr.io/container-suite/crunchy-pgbackrest:ubi8-13.2-ci-latest
      repoHost:
        dedicated: {}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
