apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: over
spec:
  users:
  - name: overuser
    databases:
        - overdb
        - underdb
  image: registry.crunchydata.com/crunchydata/crunchy-postgres:ubi8-13.4-1
  imagePullSecrets: 
    - name: crunchy-registry
  openshift: false
  port: 5432
  postgresVersion: 13
  instances:
    - name: 'pgc'
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi

  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_parallel_workers: 2
          max_worker_processes: 2
          shared_buffers: 256MB
          work_mem: 10MB
          archive_timeout: 120
