apiVersion: v1
kind: Service
metadata:
  name: over-lb
spec:
  selector:
    postgres-operator.crunchydata.com/role: master
    postgres-operator.crunchydata.com/cluster: over-prod
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
