apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: over
spec:
  instances:
    - name: 'pgc'
      replicas: 3
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi

  standby:
    enabled: false
    repoName: repo2

  backups:
    pgbackrest:
      global:
        repo1-path: /pgbackrest/repo1
        repo2-path: /pgbackrest/zoo/over/repo2
      manual:
        repoName: repo2
        options:
         - --type=full
      configuration:
      - secret:
           name: pgo-s3-creds-prod
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * 0"
          incremental: "0 1 * * 1-6"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
      - name: repo2
        schedules:
          full: "0 1 * * 6"
        s3:
          bucket: "<bucket>"
          endpoint: "s3.amazonaws.com"
          region: "us-east-2"

  monitoring:
    pgmonitor:
      exporter:
        image: registry.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.0.3-0

  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          archive_timeout: 600
