---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "install.roleBindingKind" . }}
metadata:
  name: {{ include "install.roleBindingName" . }}
  labels:
    {{- include "install.labels" . | nindent 4 }}
    {{- include "install.clusterLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "install.roleKind" . }}
  name: {{ include "install.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "install.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "install.roleBindingKind" . }}
metadata:
  name: {{ include "install.roleBindingName" . }}-upgrade
  labels:
    {{- include "install.labels" . | nindent 4 }}
    {{- include "install.upgradeLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "install.roleKind" . }}
  name: {{ include "install.roleName" . }}-upgrade
subjects:
- kind: ServiceAccount
  name: {{ include "install.serviceAccountName" . }}-upgrade
  namespace: {{ .Release.Namespace }}
