apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "install.labels" . | nindent 4 }}
    {{- include "install.clusterLabels" . | nindent 4 }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "install.clusterLabels" . | nindent 4 }}
