---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "install.serviceAccountName" . }}
  labels:
    {{- include "install.labels" . | nindent 4 }}
    {{- include "install.clusterLabels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "install.serviceAccountName" . }}-upgrade
  labels:
    {{- include "install.labels" . | nindent 4 }}
    {{- include "install.upgradeLabels" . | nindent 4 }}
