apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: crunchy-alertmanager

resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
- files:
  - config/alertmanager.yml
  name: alertmanager-config

generatorOptions:
  disableNameSuffixHash: true
