commonLabels:
  app.kubernetes.io/component: crunchy-alertmanager

resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- serviceaccount.yaml

configMapGenerator:
  - name: alertmanager-config
    files:
      - "config/alertmanager.yml"

generatorOptions:
  disableNameSuffixHash: true
