apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
  name: {{ .Values.prometheusDeploymentName }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "monitoring.labels" . | nindent 6 }}
      name: {{ .Values.prometheusDeploymentName }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "monitoring.labels" . | nindent 8 }}
        name: {{ .Values.prometheusDeploymentName }}
    spec:
      containers:
      - image: prom/prometheus:v2.33.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: prometheus
        ports:
        - containerPort: 9090
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheusconf
        - mountPath: /prometheus
          name: prometheusdata
        - mountPath: /etc/prometheus/alert-rules.d
          name: alertmanagerrules
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 26
        # supplementalGroups:
        # - 65534
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: {{ .Values.prometheusServiceAccountName }}
      serviceAccountName: {{ .Values.prometheusServiceAccountName }}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Values.prometheusConfigmapName }}
        name: prometheusconf
      - name: prometheusdata
        persistentVolumeClaim:
          claimName: {{ .Values.prometheusPVCName }}
      - configMap:
          defaultMode: 420
          name: {{ .Values.alertmanagerRuleConfigmapName }}
        name: alertmanagerrules

