apiVersion: v1
data:
  password: YWRtaW4=
  username: YWRtaW4=
kind: Secret
metadata:
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
  name: {{ .Values.grafanaSecretName }}
type: Opaque

