---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: operator
        image: postgres-operator
        env:
        - name: CRUNCHY_DEBUG
          value: "true"
        - name: PGO_DISABLE_PGCLUSTER
          value: "true"
        - name: CRUNCHY_POSTGRES_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      serviceAccount: postgres-operator
