---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgo-upgrade
spec:
  template:
    spec:
      containers:
      - name: operator
        env:
        - name: PGO_TARGET_NAMESPACE
          valueFrom: { fieldRef: { apiVersion: v1, fieldPath: metadata.namespace } }
