name: Upstream to PR

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  autoupdate:
    uses: neuro-inc/reuse/.github/workflows/auto-pr.yaml@master
    with:
      upstream_repository: https://github.com/CrunchyData/postgres-operator-examples
      upstream_branch: 'main'
    secrets:
      personal_access_token: ${{ secrets.GH_AUTO_PR }}